// This file was autogenerated by closure/library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../development/js_dev/app.js', ['ffosapp.App'], ['ffosapp.geo', 'goog.debug.DivConsole', 'goog.debug.FpsDisplay', 'goog.debug.Logger', 'goog.dom', 'goog.events', 'goog.events.EventType', 'goog.format.JsonPrettyPrinter', 'goog.json']);
goog.addDependency('../../../../development/js_dev/geo/geo.js', ['ffosapp.geo'], []);
goog.addDependency('../../../../development/js_dev/main.js', ['ffosapp.main'], ['ffosapp.App']);
